# The title of the photoalbum
TITLE='Irregular Ninja'

# Thumbnail height geometry
THUMBHEIGHT=400
# Normal geometry height when viewing a photo.
HEIGHT=1800
# Max previews per page.
MAXPREVIEWS=40
# Parallel ImageMagick jobs.
IMAGE_JOBS=3

# Randomly shuffle all previews.
SHUFFLE=yes
# Generate a no-JavaScript splash landing page at index.html.
SPLASH_PAGE=yes
# Set to any non-empty value for repeatable output.
# RANDOM_SEED=irregular-ninja

# Directories.
INCOMING_DIR=$(readlink -f incoming)
DIST_DIR=$(pwd)/dist
TEMPLATE_DIR=/usr/share/shuriken/templates/default

# Includes a .tar of the incoming dir in the dist, can be yes or no.
TARBALL_INCLUDE=no
TARBALL_SUFFIX=.tar
TAR_OPTS=(-c)

# Publish destinations for `shuriken --sync`.
SYNC_DELETE=yes
SYNC_DESTINATIONS=(
    admin@fishfinger.buetow.org:/var/www/htdocs/irregular.ninja/
    admin@blowfish.buetow.org:/var/www/htdocs/irregular.ninja/
)
